COMMENT ON COLUMN acs2010_3yr.geahder.fileid IS 'Always equal to ACS Summary File identification';
COMMENT ON COLUMN acs2010_3yr.geahder.stusab IS 'State Postal Abbreviation';
COMMENT ON COLUMN acs2010_3yr.geahder.sumlevel IS 'Summary Level';
COMMENT ON COLUMN acs2010_3yr.geahder.component IS 'Geographic Component';
COMMENT ON COLUMN acs2010_3yr.geahder.logrecno IS 'Logical Record Number';
COMMENT ON COLUMN acs2010_3yr.geahder.us IS 'US';
COMMENT ON COLUMN acs2010_3yr.geahder.region IS 'Census Region';
COMMENT ON COLUMN acs2010_3yr.geahder.division IS 'Census Division';
COMMENT ON COLUMN acs2010_3yr.geahder.statece IS 'State (Census Code)';
COMMENT ON COLUMN acs2010_3yr.geahder.state IS 'State (FIPS Code)';
COMMENT ON COLUMN acs2010_3yr.geahder.county IS 'County of current residence';
COMMENT ON COLUMN acs2010_3yr.geahder.cousub IS 'County Subdivision (FIPS)';
COMMENT ON COLUMN acs2010_3yr.geahder.place IS 'Place (FIPS Code)';
COMMENT ON COLUMN acs2010_3yr.geahder.tract IS 'Census Tract';
COMMENT ON COLUMN acs2010_3yr.geahder.blkgrp IS 'Block Group';
COMMENT ON COLUMN acs2010_3yr.geahder.concit IS 'Consolidated City';
COMMENT ON COLUMN acs2010_3yr.geahder.aianhh IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land (Census)';
COMMENT ON COLUMN acs2010_3yr.geahder.aianhhfp IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land (FIPS)';
COMMENT ON COLUMN acs2010_3yr.geahder.aihhtli IS 'American Indian Trust Land/ Hawaiian Home Land Indicator';
COMMENT ON COLUMN acs2010_3yr.geahder.aitsce IS 'American Indian Tribal Subdivision (Census)';
COMMENT ON COLUMN acs2010_3yr.geahder.aits IS 'American Indian Tribal Subdivision (FIPS)';
COMMENT ON COLUMN acs2010_3yr.geahder.anrc IS 'Alaska Native Regional Corporation (FIPS)';
COMMENT ON COLUMN acs2010_3yr.geahder.cbsa IS 'Metropolitan and Micropolitan Statistical Area';
COMMENT ON COLUMN acs2010_3yr.geahder.csa IS 'Combined Statistical Area';
COMMENT ON COLUMN acs2010_3yr.geahder.metdiv IS 'Metropolitan Statistical Area-Metropolitan Division';
COMMENT ON COLUMN acs2010_3yr.geahder.macc IS 'Metropolitan Area Central City';
COMMENT ON COLUMN acs2010_3yr.geahder.memi IS 'Metropolitan/Micropolitan Indicator Flag';
COMMENT ON COLUMN acs2010_3yr.geahder.necta IS 'New England City and Town Area';
COMMENT ON COLUMN acs2010_3yr.geahder.cnecta IS 'New England City and Town Combined Statistical Area';
COMMENT ON COLUMN acs2010_3yr.geahder.nectadiv IS 'New England City and Town Area Division';
COMMENT ON COLUMN acs2010_3yr.geahder.ua IS 'Urban Area';
COMMENT ON COLUMN acs2010_3yr.geahder.blank1 IS 'Reserved for future use';
COMMENT ON COLUMN acs2010_3yr.geahder.cdcurr IS 'Current Congressional District ***';
COMMENT ON COLUMN acs2010_3yr.geahder.sldu IS 'State Legislative District Upper';
COMMENT ON COLUMN acs2010_3yr.geahder.sldl IS 'State Legislative District Lower';
COMMENT ON COLUMN acs2010_3yr.geahder.blank2 IS 'Reserved for future use';
COMMENT ON COLUMN acs2010_3yr.geahder.blank3 IS 'Reserved for future use';
COMMENT ON COLUMN acs2010_3yr.geahder.zcta5 IS '5-digit ZIP Code Tabulation Area';
COMMENT ON COLUMN acs2010_3yr.geahder.submcd IS 'Subminor Civil Division (FIPS)';
COMMENT ON COLUMN acs2010_3yr.geahder.sdelm IS 'State-School District (Elementary)';
COMMENT ON COLUMN acs2010_3yr.geahder.sdsec IS 'State-School District (Secondary)';
COMMENT ON COLUMN acs2010_3yr.geahder.sduni IS 'State-School District (Unified)';
COMMENT ON COLUMN acs2010_3yr.geahder.ur IS 'Urban/Rural';
COMMENT ON COLUMN acs2010_3yr.geahder.pci IS 'Principal City Indicator';
COMMENT ON COLUMN acs2010_3yr.geahder.blank5 IS 'Reserved for future use';
COMMENT ON COLUMN acs2010_3yr.geahder.blank6 IS 'Reserved for future use';
COMMENT ON COLUMN acs2010_3yr.geahder.puma5 IS 'Public Use Microdata Area - 5% File';
COMMENT ON COLUMN acs2010_3yr.geahder.blank7 IS 'Reserved for future use';
COMMENT ON COLUMN acs2010_3yr.geahder.geoid IS 'Geographic Identifier';
COMMENT ON COLUMN acs2010_3yr.geahder.name IS 'Area Name';
COMMENT ON COLUMN acs2010_3yr.geahder.bttr IS 'Tribal Tract';
COMMENT ON COLUMN acs2010_3yr.geahder.btbg IS 'Tribal Block Group';
COMMENT ON COLUMN acs2010_3yr.geahder.blank8 IS 'Reserved for future use';

